### ISSUE TITLE
Module has no attribute called Device

### ISSUE THREAD

**Issue by zoharcochavi** [leddartech/LeddarSDK#10]
There is a problem in the devices.py file, where the module 'leddar' doesn't have a class called 'Device'. I have followed the complete readme and reistalled the python packages. I ran the example.launch file. Here is the output:

```
$ roslaunch leddar_ros example.launch param1:=AK14050 device_type:=M16                                                                                      

... logging to /home/zohar/.ros/log/297067cc-2274-11ea-9f34-3c9509b24e2d/roslaunch-Bunnker-3808.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Bunnker:46177/

SUMMARY
========

PARAMETERS
 * /LeddarTech_1/sensor/device_type: M16
 * /LeddarTech_1/sensor/frame_id: sensor_frame
 * /LeddarTech_1/sensor/param1: AK14050
 * /LeddarTech_1/sensor/param3: 0
 * /LeddarTech_1/sensor/param4: 0
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /LeddarTech_1/
    leddar_1_to_map (tf/static_transform_publisher)
    sensor (leddar_ros/device.py)
  /
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [3819]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 297067cc-2274-11ea-9f34-3c9509b24e2d
process[rosout-1]: started with pid [3830]
started core service [/rosout]
process[LeddarTech_1/sensor-2]: started with pid [3833]
process[LeddarTech_1/leddar_1_to_map-3]: started with pid [3834]
process[rviz-4]: started with pid [3840]
[ INFO] [1576769291.968983818]: rviz version 1.13.5
[ INFO] [1576769291.969128917]: compiled against Qt version 5.9.5
[ INFO] [1576769291.969172033]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1576769292.002992071]: Forcing OpenGl version 0.
[ INFO] [1576769292.790506010]: Stereo is NOT SUPPORTED
[ INFO] [1576769292.790731038]: OpenGl version: 4.5 (GLSL 4.5).
Traceback (most recent call last):
  File "/home/zohar/Documents/Work/ACR/rossystem/src/leddar_ros/scripts/device.py", line 39, in <module>
    dev = leddar.Device()
AttributeError: 'module' object has no attribute 'Device'
[LeddarTech_1/sensor-2] process has died [pid 3833, exit code 1, cmd /home/zohar/Documents/Work/ACR/rossystem/src/leddar_ros/scripts/device.py __name:=sensor __log:=/home/zohar/.ros/log/297067cc-2274-11ea-9f34-3c9509b24e2d/LeddarTech_1-sensor-2.log].
log file: /home/zohar/.ros/log/297067cc-2274-11ea-9f34-3c9509b24e2d/LeddarTech_1-sensor-2*.log
```

I think the problem lies with python not recognizing the module, but I'm not sure why that would be the case, since the other installed modules work just fine. I hope you could help me figure out what the problem is, or in what direction to look for answers.
Thanks in advance!

**Comment by zoharcochavi** [comment]
I double checked. Python recognized the leddar and leddar_utils library
```
>>> help("modules")

Please wait a moment while I gather a list of all available modules...

/usr/lib/python2.7/dist-packages/matplotlib/cbook/deprecation.py:106: MatplotlibDeprecationWarning: The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
BaseHTTPServer      code                mhlib               rqt_py_console
(...)
bdb                 laser_geometry      rosserial_arduino   weakref
binascii            leddar              rosserial_client    webbrowser
binhex              leddar_utils        rosserial_msgs      wheel
bisect              lib2to3             rosserial_python    whichdb
(...)
cmath               md5                 rqt_publisher       zlib
cmd                 message_filters     rqt_py_common       

Enter any module name to get more help.  Or, type "modules spam" to search
for modules whose descriptions contain the word "spam"

>>>
```

**Comment by support-leddartech** [comment]
Hi @zoharcochavi !

Could you please contact us at support@leddartech.com so we can open a support ticket and investigate this issue with you ? 

Thank you,

~ LeddarTech Support Team

**Comment by kinglolo** [comment]
Hi, I am also facing the same issue.
this shows in my console after I run example.launch :

process[rviz-3]: started with pid [12552]
[ INFO] [1577352846.661665519]: rviz version 1.13.4
[ INFO] [1577352846.661729977]: compiled against Qt version 5.9.5
[ INFO] [1577352846.661752194]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1577352846.674990030]: Forcing OpenGl version 0.
Traceback (most recent call last):
File "/home/weitinglo/catkin_ws/src/leddar_ros/scripts/device.py", line 39, in
dev = leddar.Device()
AttributeError: 'module' object has no attribute 'Device'

If there is a solution for this problem, please let me know as well :).
Thanks in advance!

**Comment by zoharcochavi** [comment]
Sorry, I completely forgot to post a solution to the problem! The original github repository on the leddar_ros package has a solution. plus a (in my opinion) better installation guide: https://github.com/mcgill-robotics/ros-leddar. If this doesn't work, I have a solution in my own github repository explaining the issue https://github.com/zoharcochavi/ACR/issues/1. Hope this helps!
