### ISSUE TITLE
Error Runing Leddar Example - ROS Kineitc

### ISSUE THREAD

**Issue by marcel7797** [leddartech/LeddarSDK#27]
Good Morning, 
I'm facing the following issue and hopping that someone knows whats happening I'm posting it here. 
I'm working with Ubuntu 16.04 LTS and ROS kinetic.

All my ROS packages have compiled successfully and to the extent of my knowledge I have implemented all the steps that are in the Leddar_ROS README file inside the LeddarSDK. This error appears with and without the LIDAR connected via USB. The rules for reading the LIDAR seem to be implemented correctly. Rviz opens but does not present anything. 

The following lines contain the roslaunch call and the error.

Thanks a lot!

ERROR:

ImportError: /home/marcel/.python-eggs/leddar-1.0-py2.7-linux-x86_64.egg-tmp/leddar.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev
[LeddarTech_1/sensor-2] process has died [pid 3611, exit code 1, cmd /home/marcel/catkin_ws/src/leddar_ros/scripts/device.py __name:=sensor __log:=/home/marcel/.ros/log/c3cf0a04-9202-11eb-9415-00215de11b04/LeddarTech_1-sensor-2.log].
log file: /home/marcel/.ros/log/c3cf0a04-9202-11eb-9415-00215de11b04/LeddarTech_1-sensor-2*.log

---------------------

marcel@v:~/catkin_ws$ roslaunch leddar_ros example.launch param1:=AK43004 device_type:=Vu8

... logging to /home/marcel/.ros/log/c3cf0a04-9202-11eb-9415-00215de11b04/roslaunch-v-3585.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:42139/

SUMMARY
========

PARAMETERS
 * /LeddarTech_1/sensor/device_type: Vu8
 * /LeddarTech_1/sensor/frame_id: sensor_frame
 * /LeddarTech_1/sensor/param1: AK43004
 * /LeddarTech_1/sensor/param3: 0
 * /LeddarTech_1/sensor/param4: 0
 * /rosdistro: kinetic
 * /rosversion: 1.12.17

NODES
  /LeddarTech_1/
    leddar_1_to_map (tf/static_transform_publisher)
    sensor (leddar_ros/device.py)
  /
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [3595]
ROS_MASTER_URI=http://localhost:1131

setting /run_id to c3cf0a04-9202-11eb-9415-00215de11b04
process[rosout-1]: started with pid [3608]
started core service [/rosout]
process[LeddarTech_1/sensor-2]: started with pid [3611]
process[LeddarTech_1/leddar_1_to_map-3]: started with pid [3626]
process[rviz-4]: started with pid [3637]
[ INFO] [1617182616.750832872]: rviz version 1.12.17
[ INFO] [1617182616.751343270]: compiled against Qt version 5.5.1
[ INFO] [1617182616.751639465]: compiled against OGRE version 1.9.0 (Ghadamon)
Traceback (most recent call last):
  File "/home/marcel/catkin_ws/src/leddar_ros/scripts/device.py", line 3, in <module>
    import leddar
  File "build/bdist.linux-x86_64/egg/leddar.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/leddar.py", line 6, in __bootstrap__
ImportError: /home/marcel/.python-eggs/leddar-1.0-py2.7-linux-x86_64.egg-tmp/leddar.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev
[LeddarTech_1/sensor-2] process has died [pid 3611, exit code 1, cmd /home/marcel/catkin_ws/src/leddar_ros/scripts/device.py __name:=sensor __log:=/home/marcel/.ros/log/c3cf0a04-9202-11eb-9415-00215de11b04/LeddarTech_1-sensor-2.log].
log file: /home/marcel/.ros/log/c3cf0a04-9202-11eb-9415-00215de11b04/LeddarTech_1-sensor-2*.log
[ INFO] [1617182617.189895897]: Stereo is NOT SUPPORTED
[ INFO] [1617182617.190316899]: OpenGl version: 2.1 (GLSL 1.2).

**Comment by dominiqueplourde** [comment]
Hi, 

Could you please write to support@leddartech.com so we can track this problem with you and support you better?

Thanks and regards,
Dominique

**Comment by marcel7797** [comment]
> Hi,
> 
> Could you please write to [support@leddartech.com](mailto:support@leddartech.com) so we can track this problem with you and support you better?
> 
> Thanks and regards,
> Dominique

Okay, I'll do it. Thanks!
